name: Tryout

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to be deployed'
        required: true
        default: 'origination'
        type: choice
        options:
        - origination
        - servicing
        - party
      java:
        description: 'Java verion'
        required: true
        default: '17'
        type: choice
        options:
        - 17
        - 11
      
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-test
      - name: Make the script files executable
        run: chmod +x testShellScript.sh
      - name: test shell script
        run: ./testShellScript.sh
